# Generated by Django 2.1.4 on 2019-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
